name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Execute remote command
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_HOST }}" "comando_a_ser_executado"
