name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 400 ~/.ssh/id_rsa.pem
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Execute remote command
        run: |
          ssh -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no "${{ secrets.SSH_HOST }}" "comando_a_ser_executado"
