name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: jovemhero/todopython-api:latest
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker stop todopython-api || true
            docker rm todopython-api || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todopython-api:latest
            docker run -d --name todopython-api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/todopython-api:latest
