on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Copy SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.SSH_HOST }} << 'EOF'
          mkdir -p /home/ec2-user/app
          scp -i private_key.pem -r ./server ec2-user@${{ secrets.SSH_HOST }}:/home/ec2-user/app
          cd /home/ec2-user/app/server
          docker-compose down
          docker-compose pull
          docker-compose up -d
        EOF
