name: Deploy Python App in AWS EC2

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: jovemhero/todopython-api:latest
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker stop todopython-api || true
            docker rm todopython-api || true
            docker image rm jovemhero/todopython-api:latest || true
            docker pull jovemhero/todopython-api:latest
            docker run -d --name todopython-api -e SECRET_TOKEN_EMAIL=${{ secrets.SECRET_TOKEN_EMAIL }} -e EMAIL=${{ secrets.EMAIL }} -e PASS_EMAIL=${{ secrets.PASS_EMAIL }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} -e SECRET_TOKEN=${{ secrets.SECRET_TOKEN }} -e R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} -e R2_ENDPOINT_URL=${{ secrets.R2_ENDPOINT_URL }} -e R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }} -e R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} -e DB_PORT=${{ secrets.DB_PORT }} -p 5000:5000 jovemhero/todopython-api:latest
