name: Deploy NextJS App in AWS EC2

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: jovemhero/todo-python-front:latest
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker stop todo-python-front || true
            docker rm todo-python-front || true
            docker image rm ${{ secrets.DOCKER_USERNAME }}/todo-python-front:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-python-front:latest
            docker run -d --name todo-python-front -e NEXT_PUBLIC_API_URL=${{ secrets.API_URL }} -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/todo-python-front:latest
